# Generated by Django 5.2.4 on 2026-03-27 11:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('PASSAGEIRO', 'Passageiro'), ('MOTORISTA', 'Motorista'), ('ADMIN', 'Administrador')], default='PASSAGEIRO', max_length=20)),
                ('telefone', models.CharField(max_length=20, null=True, unique=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_latitude', models.FloatField()),
                ('origem_longitude', models.FloatField()),
                ('destino_latitude', models.FloatField()),
                ('destino_longitude', models.FloatField()),
                ('origem_endereco', models.CharField(max_length=255)),
                ('destino_endereco', models.CharField(max_length=255)),
                ('preco_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia_km', models.FloatField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Motorista'), ('ACEITA', 'Motorista a Caminho'), ('EM_CURSO', 'Em Viagem'), ('CONCLUIDA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_pedidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('corrida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.corrida')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carta', models.CharField(max_length=50)),
                ('placa_veiculo', models.CharField(max_length=20)),
                ('modelo_veiculo', models.CharField(max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('latitude_atual', models.FloatField(blank=True, null=True)),
                ('longitude_atual', models.FloatField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='corrida',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_realizadas', to='usuarios.motorista'),
        ),
    ]
