# Generated by Django 5.2.4 on 2026-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
