# Generated by Django 5.2.4 on 2026-04-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_codigo_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='foto_carta_conducao',
            field=models.ImageField(blank=True, null=True, upload_to='motoristas/docs/'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto_documento_id',
            field=models.ImageField(blank=True, null=True, upload_to='motoristas/docs/'),
        ),
    ]
